# Generated by Django 2.1.1 on 2018-10-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='snappide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.CharField(max_length=225)),
                ('textfield', models.CharField(max_length=225)),
                ('label', models.CharField(max_length=25)),
                ('rating', models.IntegerField()),
                ('switch', models.BooleanField(default=True)),
            ],
        ),
    ]
